---
#Playbook to install apache only on the servers that are ubuntu distribution
#(consolidated version)

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php support packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
