---
#Playbook to work with tags

- hosts: all
  become: true
#  pre_tasks:

#  - name: install updates (Ubuntu)
#    tags: always
#    apt:
#      upgrade: dist
#      update_cacche: yes
#    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

#  - name: install apache2 and php support packages
#    tags: apache,apache2,ubuntu
#    apt:
#      name:
#        - apache2
#        - libapache2-mod-php
#      state: latest
#    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

